services:
  # 应用服务
  web-hosting-platform:
    image: crpi-m3hn355t33qhadnd.cn-hangzhou.personal.cr.aliyuncs.com/yunmind/web-hosting-platform:latest     #原始镜像位置 dockerhub中之前最新的没有错误的。
    #image: hanshuai23/web-hosting-platform:backup    备份的镜像位置
    volumes:
      - ./server/prisma/production.db:/app/server/prisma/dev_v2.db
      - ./server/prisma/migrations:/app/server/prisma/migrations
      - ./server/uploads:/app/server/uploads
      - ./server/.env:/app/server/.env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
    networks:
      - web-network
  
  # Nginx 反向代理服务
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro   # 必须挂载这个！Let's Encrypt 生成的证书在这里
    depends_on:
      - web-hosting-platform
    restart: unless-stopped
    networks:
      - web-network

  # Redis 服务 (用于短信验证码、限流、缓存)
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - web-network

volumes:
  redis_data:

networks:
  web-network:
    driver: bridge